

---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-client-secret3
type: Opaque
data:
  clientSecret: "JDJhJDEyJDZEZC9oVWVwUy9udkNvU2ZsanhDM08xS2R3QU1UM0RabE9abDQuVzU1Mk5NRkVUZ0hxZkZh"  #  kc hash secret3 -r | base64

