apiVersion: kubauth.kubotal.io/v1alpha1
kind: OidcClient
metadata:
  name: private
spec:
  redirectURIs:
    - "http://127.0.0.1:9921/callback"
  grantTypes: [ "refresh_token", "authorization_code" ]
  responseTypes: [ "id_token", "code", "token", "id_token token", "code id_token", "code token", "code id_token token" ]
  scopes: [ "openid", "offline", "profile", "groups", "email", "offline_access" ]
  description: A test OIDC private client
  secrets:
    - name: oidc-client-secret
      key: clientSecret
    - name: oidc-client-secret2
      key: clientSecret
    - name: oidc-client-secret3
      key: clientSecret
      hashed: true
  # public: false
  # accessTokenLifespan: 1h
  # refreshTokenLifespan: 1h
  # idTokenLifespan: 1h
