oidc:
  issuer: https://kubauth.ingress.kubo2.mbp
  postLogoutURL: https://kubauth.ingress.kubo2.mbp/index
  allowPasswordGrant: true
  jwtAccessToken: false

  ingress:
    enabled: true
    host: kubauth.ingress.kubo2.mbp

  server:
    certificateIssuer: cluster-odp


  image:
    pullPolicy: Always


audit:
  image:
    pullPolicy: Always

ucrd:
  image:
    pullPolicy: Always
