---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-oidc-client-secret
  namespace: kubauth
type: Opaque
stringData:
  clientSecret: "k8s123"

---
apiVersion: kubauth.kubotal.io/v1alpha1
kind: OidcClient
metadata:
  name: k8s
  namespace: kubauth
spec:
  description: For kubernetes kubectl access
  grantTypes: ["refresh_token", "authorization_code", "password"]
  redirectURIs:
    - http://localhost:8000
    - http://localhost:18000
  responseTypes: [ "id_token", "code", "token", "id_token token", "code id_token", "code token", "code id_token token" ]
  scopes: [ "openid", "offline", "profile", "groups", "email", "offline_access" ]
  accessTokenLifespan: 1m0s
  idTokenLifespan: 1m0s
  refreshTokenLifespan: 30m0s
  secrets:
    - name: k8s-oidc-client-secret
      key: clientSecret

