
ingress:
  host: kubeconfig.ingress.kubo2.mbp
server:
  tls: true
  certificateIssuer: cluster-odp
networkPolicies:
  enabled: true
kubeconfigs:
  default:
    description: Default OIDC client configuration
    cluster:
      apiServerURL: https://127.0.0.1:5448
    context:
      name: oidc-kubo2
      namespace:  # Left blank to allow default context for users
    oidc:
      issuerURL: https://kubauth.ingress.kubo2.mbp
      issuerCaSecretName: certs-bundle
      issuerCaName: ca.crt
      clientId: k8s
      clientSecret: k8s123