---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-oidc-client-secret
  namespace: kubauth
type: Opaque
stringData:
  clientSecret: "argocd123"

---
apiVersion: kubauth.kubotal.io/v1alpha1
kind: OidcClient
metadata:
  name: argocd
  namespace: kubauth
spec:
  redirectURIs:
    - "https://argocd.ingress.kubo2.mbp/auth/callback"
    - "http://localhost:8085/auth/callback"
  grantTypes: [ "refresh_token", "authorization_code" ]
  responseTypes: ["id_token", "code", "token", "id_token token", "code id_token", "code token", "code id_token token"]
  scopes: [ "openid", "offline", "profile", "groups", "email", "offline_access"]
  displayName: ArgoCD
  description: GitOps continuous delivery tool
  entryURL: https://argocd.ingress.kubo2.mbp/
  secrets:
    - name: argocd-oidc-client-secret
      key: clientSecret

